### ISSUE TITLE
crm_vocab extension

### ISSUE THREAD

**Issue by KarlPineau** [thegetty/crom#28]
Hi :)

I've started to use Crom, really great tool 👍 

I would like to extend it in order to be able to manage CRMinf. I've started to edit crm_vocab.tsv but I've few questions about it: 

- Is it possible to add class with no superclass? I try to add E59_Primitive_Value (http://www.cidoc-crm.org/Entity/e59-primitive-value/version-6.2), which doesn't have superclass but Crom doesn't like it unless I relate it to E1_CRM_Entity
- What is the purpose of the values "koh" and "okay" of property lines?
- Is it specific rules to create the inverse properties? Especially to name it?

Thanks a lot!
Karl

**Comment by azaroth42** [comment]
You can't add classes without a superclass, they need to be at least E1s.  E59 Primitive Value (and other values) don't map into RDF at all, they become literals.

Instead of tweaking the TSV directly, you could look at the code in utils/.  It processes the RDF/XML ontologies in utils/data/ ... it shouldn't be too hard to add CRMInf (or other extensions).

KOH  is Key Order Hash (or KOI for key order integer) -- In which order do you want the keys to appear in the JSON. It's only useful for documentation and making human readable output, rather than output intended for machine use only.

okay is whether to allow the property to be used. 0 is don't use it, 1 is allow it, and 2 is allow it but warn that it's not good to use.

The inverse properties from the ontology files in utils/data/.  I wrote a script (make_inverses.py) to generate inverses.xml which then adds the inverse relationships to the rdfs ontology.

**Comment by azaroth42** [comment]
(As this isn't an actual issue, the response above closes it :) )

**Comment by KarlPineau** [comment]
Hi,
Thanks for those explanations. I succeeded to integrate CRMinf, now I'm starting to integrate FRBRoo. I will look at utils/ for this one.
Thanks!
